# Generated by Django 4.1.2 on 2022-10-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_avatar_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='standart_avatar.png', null=True, upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
