# Generated by Django 4.1 on 2022-08-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('url', models.URLField(max_length=120, verbose_name='URL файла для загрузки')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('full_txt', models.TextField(verbose_name='Полное описание')),
                ('version', models.CharField(max_length=6, verbose_name='Версия майна')),
                ('type', models.CharField(max_length=12, verbose_name='Тип файла/файлов')),
                ('datetime', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
