# Generated by Django 4.1 on 2022-10-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='type',
        ),
        migrations.RemoveField(
            model_name='files',
            name='version',
        ),
    ]
