# Generated by Django 4.1.2 on 2022-10-24 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0004_alter_type_options_alter_version_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
