# Generated by Django 4.1.2 on 2022-11-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_comment_options_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='files.type'),
        ),
        migrations.RemoveField(
            model_name='files',
            name='version',
        ),
        migrations.AddField(
            model_name='files',
            name='version',
            field=models.ManyToManyField(null=True, related_name='files', to='files.version'),
        ),
    ]
