# Generated by Django 4.1.2 on 2022-11-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_alter_files_type_remove_files_version_files_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='version',
            field=models.ManyToManyField(related_name='files', to='files.version'),
        ),
    ]
